Repository akanshSirohi/Github-Cards-API, pull requests merged in 2023-10, with the labels that each got.

#28 add : new card [word-of-the-day-card]
  README.md
  index.js
  package-lock.json
  src/cards/word_of_the_day.js
  src/data/word_of_the_day.json
  src/help.js
  yarn.lock
Labels: hacktoberfest

#31 New card challenge of the week
  README.md
  index.js
  src/cards/challenge-of-the-week.js
  src/data/challenge_of_the_week.json
  src/help.js
Labels: hacktoberfest

#34 Picks randomly from every category
  index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, something-new

#40 new theme added
  README.md
  src/gradients.js
  src/help.js
  src/themes.js
Labels: enhancement, hacktoberfest

#41 added bhagavad-geeta-card
  README.md
  index.js
  src/cards/bhagavad-geeta-quotes.js
  src/data/bhagavad_geeta_quotes.json
  src/help.js
Labels: enhancement, good first issue, hacktoberfest

#43 new theme added
  src/gradients.js
  src/help.js
  src/themes.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 [ADDED]: New card named programming-facts-card has been added
  README.md
  index.js
  package-lock.json
  src/cards/programming-facts.js
  src/data/programming_facts.json
  src/help.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#50 Added: Card level HTML card generation support
  src/card-generator.js
  src/cards/motivational-quote.js
  src/satori_renderer.js
Labels: hacktoberfest
