Repository akanshSirohi/Github-Cards-API, pull requests merged in 2024-10, with the labels that each got.

#59 Neon Theme
  src/cards/motivational-quote.js
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#63 README formatting updates
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#60 spanish quotes jokes
  .gitignore
  README.md
  index.js
  src/cards/spanish-quote.js
  src/data/spanish_jokes.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 feat/add-github-facts
  index.js
  package-lock.json
  src/cards/github-facts.js
  src/data/github_facts.json
  src/help.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#74 Added random-facts-card and fixed README.md
  README.md
  index.js
  src/cards/random-facts.js
  src/data/random_facts.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#83 HTML Theme Added
  README.md
  src/card-generator.js
  src/cards/motivational-quote.js
  src/html-themes.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#75 Created Fun Fact Card
  README.md
  index.js
  package.json
  src/cards/fun-fact-card.js
  src/data/fun_facts.json
  src/help.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#88 Neon Horizon Html Theme Added
  README.md
  src/cards/programming-quote.js
  src/help.js
  src/html-themes.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#77 game of thrones quotes
  README.md
  index.js
  src/cards/got-quotes.js
  src/data/got-quotes.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#87 Added Harry Potter card following all the required steps.
  README.md
  index.js
  src/cards/harry-potter-spells.js
  src/data/harry-potter-spells.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#90 Added Galaxy theme
  README.md
  package.json
  src/gradients.js
  src/help.js
  src/themes.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, something-new

#91 Adding security tips cards
  README.md
  index.js
  src/cards/security-tips-cards.js
  src/data/security-tips.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#100 Travel Destination Cards
  README.md
  index.js
  src/cards/travel_destinations.js
  src/data/travel_destinations.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#106 Health tip card added
  README.md
  index.js
  src/cards/health-tip-card.js
  src/data/health-tips.json
  src/help.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
